// Trust gates applied at the `done` action, extracted as pure functions so they
// can be unit-tested without a browser/Anthropic (the agent loop in server.js
// needs both; THESE decisions are pure functions of their inputs). Wired into
// server.js's `case 'done'` handler. See test/done-gates.test.mjs.
//
// Why these exist: the agent is told (system-prompt Rule 11 + the scenario's own
// verify clauses) to (a) disclose when the app re-titles an entity on a state
// change — "accepting an offer turns it into a job named after the offer" — and
// (b) actually run a `verify` for any terminal-state assertion the scenario asks
// for. Both are prompt rules and both have been ignored on real runs, producing
// a report that reads like it tested the named job/closed state when it didn't.
// Prose can't enforce itself, so we enforce at the gate.

import { isCommitStep } from './sec-classify.js';

// ── Scenario name extraction ───────────────────────────────────
// Names the scenario explicitly references, in straight or curly quotes.
export function scenarioQuotedNames(scenario) {
  const out = [];
  const re = /['"‘’“”]([^'"‘’“”]{2,60})['"‘’“”]/g;
  let m;
  while ((m = re.exec(String(scenario || '')))) out.push(m[1].trim());
  return [...new Set(out)];
}

// Loose equality between a scenario name and a worked-entity label.
function labelsMatch(a, b) {
  const na = String(a || '').toLowerCase().trim();
  const nb = String(b || '').toLowerCase().trim();
  if (!na || !nb) return false;
  return na === nb || na.includes(nb) || nb.includes(na);
}

// ── Worked-entity detection ────────────────────────────────────
// Distinct entity labels the agent actually touched, read from the [ID: X] tag
// the executor stamps on record-scoped steps. Retried steps are ignored.
export function workedEntityLabels(steps) {
  const labels = new Set();
  for (const s of steps || []) {
    if (s.status === 'retry') continue;
    const hay = `${s.outcome || ''} ${s.target || ''}`;
    const id = (hay.match(/\[ID:\s*([^\]]+)\]/) || [])[1];
    if (id) labels.add(id.trim());
  }
  return [...labels];
}

// Is this label an app-auto-generated job name? This is the canonical Rule 11
// case: accepting an offer/quote mints a job titled after the offer, e.g.
// "Trabajo de presupuesto P-2026-0021" / "Job from quote Q-14".
const AUTO_JOB = /trabajo de (?:presupuesto|oferta|cotizaci[oó]n)\b|\bjob (?:from|for) (?:quote|offer|presupuesto)\b/i;
export function isAutoGeneratedJobName(label) {
  return AUTO_JOB.test(String(label || ''));
}

// ── GATE 1: undisclosed entity rename (Rule 11 enforcement) ─────
// Fires when the agent completed work on an app-auto-generated job card while
// the scenario named a DIFFERENT (custom-titled) job, and the closing summary
// does not disclose the switch. `disclosed` requires BOTH a reference to the
// renamed card AND a contrast cue ("different"/"note"/"instead"/…) — a bare
// mention of the offer code (which summaries often include innocently) is not a
// disclosure.
// The custom job title the scenario started from — the card that gets silently
// swapped. Prefer an explicit "job … titled 'X'" phrasing; fall back to the
// first quoted name that isn't already a worked entity or an auto job name.
export function scenarioJobName(scenario, names, worked) {
  const s = String(scenario || '');
  const m = s.match(/\b(?:job|trabajo)\b[^.'"‘“]{0,40}?\b(?:titled|named|called|llamad[oa]|titulad[oa])\b\s*['"‘“]([^'"’”]+)['"’”]/i)
    || s.match(/\b(?:titled|named|called|llamad[oa]|titulad[oa])\b\s*['"‘“]([^'"’”]+)['"’”]/i);
  if (m) return m[1].trim();
  return names.find(n => !isAutoGeneratedJobName(n) && !worked.some(w => labelsMatch(n, w))) || null;
}

export function detectUndisclosedRename({ scenario, steps, summary }) {
  const worked = workedEntityLabels(steps);
  const renamed = worked.find(isAutoGeneratedJobName);
  if (!renamed) return { renamed: null };

  const names = scenarioQuotedNames(scenario);
  // A rename only matters if the scenario named a job that is NOT this
  // auto-generated card (otherwise there's nothing being silently swapped).
  const scenarioJob = scenarioJobName(scenario, names, worked);
  if (!scenarioJob || isAutoGeneratedJobName(scenarioJob) || worked.some(w => labelsMatch(scenarioJob, w))) return { renamed: null };

  const sum = String(summary || '');
  const code = (renamed.match(/[A-Z]-?\d{4}-\d+/) || [])[0];
  const mentionsRenamed = sum.includes(renamed) || (code && sum.includes(code));
  const hasContrastCue = /\b(different|distinct|instead|originally|renamed|re-?titl\w*|another card|otra tarjeta|distint\w*|diferente|en lugar|note[:,]|nota[:,])\b/i.test(sum);
  const disclosed = mentionsRenamed && hasContrastCue;
  return disclosed ? { renamed: null } : { renamed, scenarioJob };
}

// The disclosure note the engine appends when the agent has been nudged once and
// still won't write it — so the report is never silently wrong.
export function renameDisclosureNote(renamed, scenarioJob) {
  return `Note: the app re-titled the work entity on offer acceptance — the job actually completed/invoiced was '${renamed}', a different card from the originally-named '${scenarioJob}'. Work continued on the card holding the materials/invoice (correct per entity-rename handling), but the named card '${scenarioJob}' was not itself driven to that state.`;
}

// ── GATE 2: terminal-state verify the scenario asked for but never ran ──
// Each entry: a terminal state the scenario can demand, with the synonyms that
// satisfy "this state was affirmed".
const TERMINAL_STATES = [
  { key: 'closed', re: /\b(closed|close the|cerrad\w*|finaliz\w*|complet\w*|terminad\w*|done)\b/i },
  { key: 'paid', re: /\b(paid|pagad\w*|abonad\w*)\b/i },
];

// Terminal states the scenario explicitly asks to VERIFY/CONFIRM (only clauses
// carrying a verify/confirm verb count — "complete the job" is an instruction to
// act, not an assertion to check).
export function requiredTerminalVerifications(scenario) {
  const s = String(scenario || '');
  const req = new Set();
  for (const clause of s.split(/(?<=[.;])\s+/)) {
    if (!/\b(verify|verif\w*|confirm|confirm\w*|ensure|check that|comprueb\w*|aseg[úu]r\w*)\b/i.test(clause)) continue;
    for (const st of TERMINAL_STATES) if (st.re.test(clause)) req.add(st.key);
  }
  return [...req];
}

// The custom client name the scenario created (companion to scenarioJobName).
export function scenarioClientName(scenario) {
  const m = String(scenario || '').match(/\bclient(?:e|a)?\b[^.'"‘“]{0,30}?\b(?:named|called|llamad[oa])\b\s*['"‘“]([^'"’”]+)['"’”]/i);
  return m ? m[1].trim() : null;
}

// ── GATE 2 v2: ENTITY BINDING ──────────────────────────────────
// The identifiers of entities THIS run actually created — the only ones a
// terminal-state verify is allowed to be "about". Without this, a `Pagada`
// verify on a STALE pre-existing invoice (a different client's, from a prior
// run) counted as coverage. Anchors = the scenario's created client + job
// titles, plus record codes (P-2026-00NN, the offer-renamed job, a freshly
// created F-2026-00NN) that appear on COMMIT steps — NOT on bare navigation
// clicks (clicking an old invoice to open it is not "creating" it, so its code
// is deliberately excluded).
export function sessionAnchors(scenario, steps) {
  const anchors = new Set();
  const client = scenarioClientName(scenario);
  if (client) anchors.add(client);
  const job = scenarioJobName(scenario, scenarioQuotedNames(scenario), workedEntityLabels(steps));
  if (job) anchors.add(job);
  for (const s of steps || []) {
    if (s.status === 'retry') continue;
    if (!isCommitStep({ action: { action: s.action, target: s.target }, outcome: s.outcome, status: s.status })) continue;
    const hay = `${s.outcome || ''} ${s.target || ''}`;
    const id = (hay.match(/\[ID:\s*([^\]]+)\]/) || [])[1];
    if (id) anchors.add(id.trim());
    for (const m of hay.matchAll(/\b[A-Z]-\d{4}-\d+\b/g)) anchors.add(m[0]);
  }
  return [...anchors].filter(a => a && a.length >= 3);
}

// Terminal states AFFIRMED by a passing verify step (❔/uncertain or failed
// verifies never count). When `anchors` is non-empty the verify must ALSO name a
// session entity (entity binding) — a verify about a stale/other entity does not
// cover the requirement. Pass null/[] to disable binding (v1 behavior).
export function coveredTerminalStates(steps, anchors = null) {
  const bind = Array.isArray(anchors) && anchors.length > 0;
  const covered = new Set();
  for (const s of steps || []) {
    if (s.action !== 'verify' || s.status === 'retry') continue;
    const hay = `${s.target || ''} ${s.outcome || ''}`;
    if (/❔|uncertain|could not|couldn'?t|no se pudo|unable/i.test(hay)) continue;
    if (bind && !anchors.some(a => hay.toLowerCase().includes(a.toLowerCase()))) continue;
    for (const st of TERMINAL_STATES) if (st.re.test(hay)) covered.add(st.key);
  }
  return covered;
}

// The required terminal verifications that no ENTITY-BOUND verify step covered.
// Empty unless the scenario demanded a terminal-state check that never ran on a
// this-session entity.
export function missingTerminalVerifications({ scenario, steps }) {
  const required = requiredTerminalVerifications(scenario);
  if (!required.length) return [];
  const covered = coveredTerminalStates(steps, sessionAnchors(scenario, steps));
  return required.filter(k => !covered.has(k));
}

// Richer view for the gate's nudge: distinguishes states never verified at all
// (`missing`) from states verified but only on a NON-session entity
// (`misbound` — the "verified a stale invoice" case), so the agent gets a
// targeted correction rather than a generic "go verify".
export function terminalVerifyDiagnostics({ scenario, steps }) {
  const required = requiredTerminalVerifications(scenario);
  const anchors = sessionAnchors(scenario, steps);
  const boundCovered = coveredTerminalStates(steps, anchors);
  const looseCovered = coveredTerminalStates(steps, null);
  const missing = required.filter(k => !boundCovered.has(k));
  const misbound = missing.filter(k => looseCovered.has(k));
  return { required, anchors, missing, misbound };
}

// A `done` summary that reports the run as blocked/failed must NOT be pushed to
// go run a terminal verify — there's nothing to verify. Gate 2 is skipped when
// this is true.
export function summaryLooksBlocked(summary, bugCount = 0) {
  if (bugCount > 0) return true;
  return /\b(blocked|could not|couldn'?t|unable|cannot|can'?t|gave? ?up|no se pudo|no fue posible)\b/i.test(String(summary || ''));
}
